services:
  squash:
    container_name: squash
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_SSL_MODE=disable
      - HOSTNAME=http://localhost:80
      # - AWS_ACCESS_KEY_ID=
      # - AWS_SECRET_ACCESS_KEY=
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    ports:
      - '5432:5432'
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  postgres_data:
    driver: local
